workflows:
  ios-workflow:
    name: TFAS Diagnostics iOS
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - ios_credentials
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --certificate-password $CM_CERTIFICATE_PASSWORD
      - name: Set up provisioning profile
        script: |
          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo $CM_PROVISIONING_PROFILE | base64 --decode > "$PROFILES_HOME/profile.mobileprovision"
      - name: Install pods
        script: pod install
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace "TFAS Diagnostics.xcworkspace" \
            -scheme "TFAS Diagnostics" \
            -configuration Release \
            -archivePath build/TFASDiagnostics.xcarchive \
            DEVELOPMENT_TEAM=H7RBA8ZZN9 \
            CODE_SIGN_STYLE=Automatic \
            archive
    artifacts:
      - build/TFASDiagnostics.xcarchive
      - "**/*.ipa"
